/*
 * The MIT License
 *
 * Automatic resource creation based on node labels by Darius Mihai (mihai_darius22@yahoo.com)
 * Copyright (C) 2015 Freescale Semiconductor, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.jenkins.plugins.lockableresources.autogen;

import hudson.model.Node;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import jenkins.model.Jenkins;
import org.jenkins.plugins.lockableresources.LockableResource;

public class Utils {

	public static String  AUTOGEN_NAME_PREFIX   = "AutoGenForNode";
	public static String  AUTOGEN_NAME_INFIX    = "WithLabels";
	public static String  AUTOGEN_DESCRIPTION   = "Automatically generated resource";
	public static boolean AUTOGEN_AUTOGENERATED = true;

	/**
	 * @return Retrieve a list of all nodes in the system, including the master node
	 */
	public static Set<Node> getAllNodes() {
		int size = Jenkins.getInstance().getNodes().size() + 1;
		Set<Node> nodes = new HashSet<Node>(size);

		nodes.addAll(Jenkins.getInstance().getNodes());
		nodes.add(Jenkins.getInstance());

		return nodes;
	}

	/**
	 * @param labelSet A set of labels required for a node to have
	 * @param node The node for which this resource is created
	 * @return A name for a automatically generated resource. The name has the following structure:
	 * AUTOGET_NAME_PREFIX_nodeName_AUTOGEN_NAME_INFIX_label1[_label2]...[_labelN]
	 */
	private static String getAutoGenResourceName(LabelSet labelSet,
												 String nodeName) {
		String name ;
		name  = AUTOGEN_NAME_PREFIX;
		name += "_" + nodeName;
		name += "_" + AUTOGEN_NAME_INFIX;

		for(String s : labelSet.getLabelsSet())
			name += "_" + s;

		return name;
	}

	/**
	 * @param node The node for which the labels are required
	 * @return A list of labels associated with the node
	 */
	private static List<String> getNodeLabels(Node node) {
		return Arrays.asList(node.getLabelString().split("\\s+"));
	}

	/**
	 * @param labelSet A set of required labels
	 * @param nodeLabels A list of labels associated with a node
	 * @return True if all the required labels are in the list of node labels
	 */
	private static boolean checkIfLabelsMatch(  LabelSet labelSet,
												List<String> nodeLabels) {
		return nodeLabels.containsAll(labelSet.getLabelsSet());
	}

	/**
	 * @param labelSets A set of 'LabelSet' variables that contains information about
	 * requested combinations of labels
	 * @return A set of "LockableResource"s that were created and reserved for a node
	 * and have the requested labels associated
	 */
	public static Set<LockableResource> autoCreateResources(Set<LabelSet> labelSets) {
		List<String> nodeLabels;
		String nodeName;
		Set<LockableResource> autoGeneratedResources = new HashSet<LockableResource>();

		for(Node node : getAllNodes()) {
			nodeLabels = getNodeLabels(node);
			nodeName = node.getNodeName().equals("") ? "master" : node.getNodeName();

			for(LabelSet ls : labelSets)
				if(checkIfLabelsMatch(ls, nodeLabels))
					autoGeneratedResources.add(new LockableResource(getAutoGenResourceName(ls, nodeName),
																	AUTOGEN_DESCRIPTION,
																	ls.getLabels(),
																	nodeName,
																	"",
																	AUTOGEN_AUTOGENERATED));
		}

		return autoGeneratedResources;
	}
}
