name: Rebase open PRs

on:
  push:
    branches:
      - master

jobs:
  rebase-prs:
    uses: mPokornyETM/rebase-open-prs-action/.github/workflows/rebase-open-prs.yml@v1
    secrets:
      GH_PAT: ${{ secrets.GH_TOKEN_PAT }}
