name: Rebase open PRs

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  rebase-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: mPokornyETM/rebase-open-prs-action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN_PAT }}
